--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/niksingh710/.wallpapers/gruvbox/wall_secondary.png"

-- Special
background="#191919"
foreground="#c5c5c5"
cursor="#c5c5c5"

-- Colors
color0="#191919"
color1="#3a3632"
color2="#582c1e"
color3="#423f39"
color4="#50473c"
color5="#634723"
color6="#5a5149"
color7="#8c8c8c"
color8="#525252"
color9="#4e4843"
color10="#763b28"
color11="#59554c"
color12="#6b5f51"
color13="#855f2f"
color14="#796d62"
color15="#c5c5c5"
