# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#c5c5c5"          # Main text color
theme[title]="#c5c5c5"            # Title color for boxes
theme[hi_fg]="#59554c"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#525252"       # Color of inactive/disabled text
theme[graph_text]="#855f2f"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]=""           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#c5c5c5"       # Background color of selected item in processes box
theme[selected_fg]="#8c8c8c"       # Foreground color of selected item in processes box
theme[proc_misc]="#855f2f"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#423f39"           # Cpu box outline color
theme[mem_box]="#3a3632"           # Memory/disks box outline color
theme[net_box]="#423f39"           # Net up/down box outline color
theme[proc_box]="#3a3632"          # Processes box outline color
theme[div_line]="#3a3632"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#525252"          # Background color of the percentage meters
theme[used_start]="#634723"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#855f2f"
theme[available_start]="#5a5149"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#796d62"
theme[cached_start]="#634723"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#855f2f"
theme[free_start]="#5a5149"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#796d62"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#59554c"        # CPU graph colors
theme[cpu_mid]="#763b28"
theme[cpu_end]="#4e4843"
theme[download_start]="#634723"    # Download graph colors
theme[download_mid]="#3a3632"
theme[download_end]="#4e4843"  
theme[upload_start]="#763b28"     # Upload graph colors
theme[upload_mid]="#582c1e"
theme[upload_end]="#5a5149"
theme[process_start]="#855f2f"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#796d62"
theme[process_end]="#50473c"
