# Shell variables
# Generated by 'wal'
wallpaper="/home/niksingh710/.wallpapers/gruvbox/wall_secondary.png"

# Special
background='#191919'
foreground='#c5c5c5'
cursor='#c5c5c5'

# Colors
color0='#191919'
color1='#3a3632'
color2='#582c1e'
color3='#423f39'
color4='#50473c'
color5='#634723'
color6='#5a5149'
color7='#8c8c8c'
color8='#525252'
color9='#4e4843'
color10='#763b28'
color11='#59554c'
color12='#6b5f51'
color13='#855f2f'
color14='#796d62'
color15='#c5c5c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
